name: Auto Commit Daily Everyday

on:
  schedule:
    - cron: "*/1 * * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  auto-commit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          ref: main

      - name: Create file and commit
        run: |
          export TZ=Asia/Ho_Chi_Minh

          TIMESTAMP=$(date '+%Y-%m-%d %H:%M:%S')
          FILE="commit_number.md"
          if [ ! -f "$FILE" ]; then
            echo "#Commit number: 1" >> "$FILE"
          else
            CURRENT_COUNT=$(grep -oP '#Commit number: \K\d+' "$FILE")
            if [ -z "$CURRENT_COUNT" ]; then
                CURRENT_COUNT=0
            fi
            NEXT_COUNT=$((CURRENT_COUNT + 1))
            sed -i "/#Commit number: /c\#Commit number: $NEXT_COUNT" "$FILE"
          fi

          git config --global user.name "Bot Commit - Le Tien Dat"
          git config --global user.email "attn110601@gmail.com"

          git add "$FILE"
          git commit -m "Auto commit at $TIMESTAMP" || echo "Nothing to commit"

          echo "🔁 Pulling latest from origin/main"
          git pull origin main --rebase || echo "⚠️ Pull failed"

          echo "📤 Pushing to GitHub..."
          git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git || echo "⚠️ Push failed"

          echo "✅ Commit at $TIMESTAMP (UTC+7)"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
